### ISSUE TITLE
Improvements for this action

### ISSUE THREAD

**Issue by Andre601** [probablykasper/readme-template#3]
While I like this action do I feel like it could receive some improvements to make it better to use.

## 1) Option to exclude forks
Placeholders such as `{{ loop 3_NEWEST_REPOS }}` include forks, which is something people like me would like to exclude.
So maybe have an option like a `with` action option to exclude forks from the lists.

## 2) Better options for loop size
I feel like only having `3_MOST_STARRED_REPOS`, `3_NEWEST_REPOS` and `3_RECENTLY_PUSHED_REPOS` for the loop placeholder is fairly limiting on what you want to show. What if someone wants to display more or less than 3 repos?

While I get that there is the option of defining or overriding placeholders is it imo not an ideal solution for everyone to have.

So perhaps have the placeholders like `{{ loop MOST_STARRED_REPOS size=3 }}` to allow a more customizable size?

**Comment by probablykasper** [comment]
For now you'd have to use custom parameters to accomplish that. In [`EXAMPLE_TEMPLATE.md`](https://github.com/probablykasper/readme-template-action/blob/v1/EXAMPLE_TEMPLATE.md) there's a `2_MOST_STARRED_REPOS` loop. To get forks excluded, I think adding `isFork: false` should work:
```
// {{ TEMPLATE: }}
module.exports = {
  "2_MOST_STARRED_REPOS": {
    type: 'repos',
    params: `
      first: 2,
      isFork: false,
      privacy: PUBLIC,
      ownerAffiliations:[OWNER],
      orderBy: { field:STARGAZERS, direction: DESC },
    `,
  }
}
// {{ :TEMPLATE }}
```

I don't think I'll be adding this anytime soon, PRs are welcome though

**Comment by Andre601** [comment]
Okay.
On a different note, how would I be able to include org repos I'm owner of for things like the 3_MOST_STARRED option?

**Comment by probablykasper** [comment]
For that, you need to use a custom query. This hopefully works:
```js
// {{ TEMPLATE: }}
module.exports = {
  LATEST_VIDL_RELEASE: {
    type: 'customQuery',
    loop: true,
    query: async (octokit, moment, user) => {
      // You can do anything  you want with the GitHub API here.
      const result = await octokit.graphql(`
        query { 
          organization(login: "rust-lang") {
            repositories(first: 3, isFork: false, privacy: PUBLIC, ownerAffiliations: [OWNER], orderBy: { field: STARGAZERS, direction: DESC } ) {
              edges {
                node {
                  name
                  stargazers { totalCount }
                  # etc
                }
              }
            }
          }
        }
      `)
      const loop = []
      const repos = result.organization.repositories.edges
      for (const repo of repos) {
        loop.push({
          REPO_NAME: repo.name
          REPO_STARS: repo.stargazers.totalCount
          // etc
        })
      }
      return loop
    }
  }
// {{ :TEMPLATE }}
```

Closing this for now

**Comment by Andre601** [comment]
Hey.

First of all, sorry for this rather late response here, was busy with a lot of other things. I just wanted to ask, if you by any chance have a URL (GitHub API Docs?) explaining and/or showcasing the returned JSON structure of such a query, to know what values I could get from it.

Like from what I get would I define the values to take from the JSON in the `edges { nodes {` part of the template to then use in the for loop later on, but without knowing the overall JSON structure to work with do I have a hard time understanding this, especially since I don't know where in the docs I should look for an example response...

I hope you can help me out here.

**Comment by probablykasper** [comment]
You can learn it in the GitHub GraphQL API explorer: https://docs.github.com/en/graphql/overview/explorer

If you don't know how to use it, just check out a tutorial on GraphQL or how GraphQL explorers work
