### ISSUE TITLE
How to get the repo name where the workflow is running?

### ISSUE THREAD

**Issue by hlinero** [probablykasper/readme-template#4]
Hello,

Thanks for this project, It is being very useful. I have encountered a new scenario that I am not sure how to handle:

Let's say I am running this workflow on a repository called `X`, how can I access the repo name `X` from the template file?

Thank you

**Comment by probablykasper** [comment]
You'd have to use a [custom query](https://github.com/probablykasper/readme-template-action#custom-queries) for that
